name: caller flow

on:
  workflow_dispatch:

jobs:
    call_reusable_flow:
        uses: ./.github/workflows/reusable-flow.yml
        with:
            deploy-to: "PRD"
        secrets: inherit

    show_output:
        runs-on: ubuntu-latest
        needs: call_reusable_flow
        steps:
            - name: Show output
              run: echo "Output from reusable flow? ${{ needs.call_reusable_flow.outputs.success }}"