name: conditional flow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get NPM cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir-$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}  
          key: npm-cache-dir-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        id: run-tests
        run: npm run fail-test -- --reporter json > test-results.json

      - name: Upload test results
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json