name: custom action demo

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Utilizando a custom action
              uses: avera-courses/custom-action-demo/checkout-install-test@main 
              with:
                use_cache: false