name: deploy dockerhub ecs

on: 
  push:
    branches: [main]  
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      versao: ${{ steps.docker_build.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get NPM Cache Directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          # pega o hash do package-lock.json por menos que seja a modificação, evitando deprecação de dependencias
          key: npm-cache-dir-${{ hashFiles('**/package-lock.json') }}  
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test

      - name: Build App
        run: npm run build

      - name: TAG Generate
        run: |
          TAG=$(date +%Y-%m-%d-%H-%M-%S)
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
#          docker build -t github-actions-site:$TAG .  
        id: docker_build

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build and Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-site:${{ steps.docker_build.outputs.tag }}      

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: echo "Deploying ${{ needs.build.outputs.versao }} to server..."  