name: explore

on:
  workflow_dispatch:    

jobs:
  workflow-info:
    runs-on: ubuntu-latest
    env: 
      HELLO_WORLD: "Hello, World"
    steps:
      - name: Explore ENV
        run: echo "${{ env.HELLO_WORLD }}"

      - name: Show Github Context
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "${{ toJson(github) }}"