name: matrix

on:
  workflow_dispatch:

jobs:
  matrix-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Testar em diferentes sistemas operacionais
        node-version: [16, 18] # Testar em diferentes versões do Node.js
        include:
          - os: ubuntu-latest
            node-version: 20
            test: true # Adiciona um teste específico para esta combinação
    runs-on: ${{ matrix.os }} # Usar o sistema operacional definido na matriz
    steps:
      
      - name: Verificar código-fonte
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }} # Definir a versão do Node.js

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Build Aplicação
        run: npm run build  