name: reusable flow

on:
   workflow_call:
        inputs:
            deploy-to:
                description: 'Environment to deploy'
                required: true
                default: 'DEV'
                type: string

jobs:
  reusable_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run reusable job
        run: |
          echo "Environment: ${{ inputs.deploy-to }}"    