name: Demo Executando Testes

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  depoy:
    needs: [run-tests]
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build app
      run: echo "Building app..."

    - name: Deploy to stage
      run: echo "Deploying to stage..."    