name: test secrets

on:   
  workflow_dispatch:
    
env:
  SECRET_ENV: ${{ secrets.SECRET_ENV }}

jobs:
  test-secret-job:
    name: Test Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Exibir Secrets
        run: |
          echo "Workflow env SECRET_ENV: $SECRET_ENV"
          echo "Super Secret: ${{ secrets.SUPER_SECRET }}"